# Generated by Django 3.0 on 2025-04-19 06:25

from django.db import migrations


def copy_profiles_data(apps, schema_editor):
    """
    Copy profiles data from the old table to the new table.
    :param apps:
    :param schema_editor:
    :return:
    """
    try:
        OldProfile = apps.get_model('oc_lettings_site', 'Profile')
        NewProfile = apps.get_model('profiles', 'Profile')

        for old_profile in OldProfile.objects.all():
            NewProfile.objects.create(
                id=old_profile.id,
                user_id=old_profile.user_id,
                favorite_city=old_profile.favorite_city,
            )
    except LookupError:
        # old models do not exist
        print("Oc_lettings_site.Profile doesn't exist anymore.")


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_profiles_data),
    ]
