# .readthedocs.yaml
version: 2

build:
  os: ubuntu-20.04
  tools:
    python:
      version: "3.9"
  jobs:
    pre_install:
      - pip install --upgrade pip
      - pip install -r requirements.txt
    post_install:
      - cd docs && make html
sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
