# noinspection YAMLSchemaValidation
services:
  - type: web
    name: oc-lettings
    env: docker
    plan: free
    repo: https://github.com/dogmatus07/oc-lettings
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        value:
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: oc-lettings.onrender.com
      - key: SENTRY_DSN
        value: