# Generated by Django 3.0 on 2025-04-18 14:10

from django.db import migrations


def copy_lettings_data(app, schema_editor):
    """
    Copy lettings data from the old table to the new table.
    :param app:
    :param schema_editor:
    :return:
    """

    OldAddress = app.get_model('oc_lettings_site', 'Address')
    OldLetting = app.get_model('oc_lettings_site', 'Letting')
    NewAddress = app.get_model('lettings', 'Address')
    NewLetting = app.get_model('lettings', 'Letting')

    for old_address in OldAddress.objects.all():
       NewAddress.objects.create(
           id=old_address.id,
           number=old_address.number,
           street=old_address.street,
           city=old_address.city,
           state=old_address.state,
           zip_code=old_address.zip_code,
           country_iso_code=old_address.country_iso_code,
       )

    for old_letting in OldLetting.objects.all():
        NewLetting.objects.create(
            id=old_letting.id,
            title=old_letting.title,
            address_id=old_letting.address_id,
        )


class Migration(migrations.Migration):
    """
    Migration to copy lettings data from the old table to the new table.
    """

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_lettings_data),
    ]
