# This is a GitHub Actions workflow file for a CI/CD pipeline.
name: CI/CD Pipeline
on:
  push:
    branches: [main, master, deploy]
    pull_request:
      branches: [main, master, deploy]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests and generate coverage report
        run: |
          pytest --cov=.

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3

  build-and-push:
      name: Build and Push Docker Image
      runs-on: ubuntu-latest
      needs: test
      if: github.event_name == 'push'

      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ secrets.DOCKER_IMAGE }}
            tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=sha

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha, mode=max
